config/routes.rb
Boilerplate::Application.routes.draw do

  namespace :admin do
    resources :users
    resources :pages
  end

  namespace :api do
    resources :counters, :only => [:index, :create]
    resources :users do
      collection do
        post :register
        post :login
      end
    end
  end

  get "welcome/index"
  get "welcome/dashboard"

  resources :foos

  match "about" => "welcome#about"
  match "team" => "welcome#team"

  root :to => 'welcome#index'

end

app/models/foo.rb
# -*- encoding : utf-8 -*-
class Foo < ActiveRecord::Base
  attr_accessible :bar, :foo
end

app/controllers/foos_controller.rb
# -*- encoding : utf-8 -*-
class FoosController < ApplicationController
  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foos }
    end
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
    @foo = Foo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/new
  # GET /foos/new.json
  def new
    @foo = Foo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/1/edit
  def edit
    @foo = Foo.find(params[:id])
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(params[:foo])

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render json: @foo, status: :created, location: @foo }
      else
        format.html { render action: "new" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foos/1
  # PUT /foos/1.json
  def update
    @foo = Foo.find(params[:id])

    respond_to do |format|
      if @foo.update_attributes(params[:foo])
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo = Foo.find(params[:id])
    @foo.destroy

    respond_to do |format|
      format.html { redirect_to foos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foos_helper.rb
# -*- encoding : utf-8 -*-
module FoosHelper
end

app/views/foos/_form.html.haml
= form_for @foo do |f|
  - if @foo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@foo.errors.count, "error")} prohibited this foo from being saved:"
      %ul
        - @foo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :foo
    = f.text_field :foo
  .field
    = f.label :bar
    = f.text_field :bar
  .actions
    = f.submit 'Save'

app/views/foos/edit.html.haml
%h1 Editing foo

= render 'form'

= link_to 'Show', @foo
\|
= link_to 'Back', foos_path

app/views/foos/index.html.haml
%h1 Listing foos

%table
  %tr
    %th Foo
    %th Bar
    %th
    %th
    %th

  - @foos.each do |foo|
    %tr
      %td= foo.foo
      %td= foo.bar
      %td= link_to 'Show', foo
      %td= link_to 'Edit', edit_foo_path(foo)
      %td= link_to 'Destroy', foo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Foo', new_foo_path

app/views/foos/new.html.haml
%h1 New foo

= render 'form'

= link_to 'Back', foos_path

app/views/foos/show.html.haml
%p#notice= notice

%p
  %b Foo:
  = @foo.foo
%p
  %b Bar:
  = @foo.bar

= link_to 'Edit', edit_foo_path(@foo)
\|
= link_to 'Back', foos_path