config/routes.rb
Boilerplate::Application.routes.draw do

  namespace :admin do
    resources :users
    resources :pages
  end

  namespace :api do
    resources :counters, :only => [:index, :create]
    resources :users do
      collection do
        post :register
        post :login
      end
    end
  end

  get "welcome/index"
  get "welcome/dashboard"

  resources :foos

  match "about" => "welcome#about"
  match "team" => "welcome#team"

  root :to => 'welcome#index'

end

app/models/counter.rb
class Counter < ActiveRecord::Base
  attr_accessible :end_at, :start_at, :times
end

app/controllers/admin/counters_controller.rb
class Admin::CountersController < Admin::BaseController
end

app/controllers/api/counters_controller.rb
class Api::CountersController < Api::BaseController

  def index
    render :json => current_user.counters.all
  end

  def create
    @counter = current_user.counters.build params[:counter]
    if @counter.save
      head 200
    else
      head 403
    end
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @counters }
    end
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
    @counter = Counter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @counter }
    end
  end

  # GET /counters/new
  # GET /counters/new.json
  def new
    @counter = Counter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @counter }
    end
  end

  # GET /counters/1/edit
  def edit
    @counter = Counter.find(params[:id])
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(params[:counter])

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render json: @counter, status: :created, location: @counter }
      else
        format.html { render action: "new" }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /counters/1
  # PUT /counters/1.json
  def update
    @counter = Counter.find(params[:id])

    respond_to do |format|
      if @counter.update_attributes(params[:counter])
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter = Counter.find(params[:id])
    @counter.destroy

    respond_to do |format|
      format.html { redirect_to counters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_form.html.haml
= form_for @counter do |f|
  - if @counter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@counter.errors.count, "error")} prohibited this counter from being saved:"
      %ul
        - @counter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :start_at
    = f.datetime_select :start_at
  .field
    = f.label :end_at
    = f.datetime_select :end_at
  .field
    = f.label :times
    = f.number_field :times
  .actions
    = f.submit 'Save'

app/views/counters/edit.html.haml
%h1 Editing counter

= render 'form'

= link_to 'Show', @counter
\|
= link_to 'Back', counters_path

app/views/counters/index.html.haml
%h1 Listing counters

%table
  %tr
    %th Start at
    %th End at
    %th Times
    %th
    %th
    %th

  - @counters.each do |counter|
    %tr
      %td= counter.start_at
      %td= counter.end_at
      %td= counter.times
      %td= link_to 'Show', counter
      %td= link_to 'Edit', edit_counter_path(counter)
      %td= link_to 'Destroy', counter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Counter', new_counter_path

app/views/counters/new.html.haml
%h1 New counter

= render 'form'

= link_to 'Back', counters_path

app/views/counters/show.html.haml
%p#notice= notice

%p
  %b Start at:
  = @counter.start_at
%p
  %b End at:
  = @counter.end_at
%p
  %b Times:
  = @counter.times

= link_to 'Edit', edit_counter_path(@counter)
\|
= link_to 'Back', counters_path